nodeLinker: node-modules

enableScripts: false
npmMinimalAgeGate: 5760
npmPreapprovedPackages:
   - "@navikt/*"
npmScopes:
   navikt:
      npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
